### ISSUE TITLE
libpasta uses yanked ring versions

### ISSUE THREAD

**Issue by scottlamb** [libpasta/libpasta#10]
I don't know why, but every version of ring older than 0.14.0 has been yanked. See crates.io:

https://crates.io/crates/ring/versions

libpasta uses `>= 0.11, < 0.13` which is now unsatisfiable.

```
$ cargo test
    Updating crates.io index
error: failed to select a version for the requirement `ring = ">= 0.11, < 0.13"`
  candidate versions found which didn't match: 0.14.2, 0.14.1, 0.14.0, ...
  location searched: crates.io index
required by package `libpasta v0.1.0-rc2`
    ... which is depended on by `moonfire-db v0.0.1 (/Users/slamb/git/moonfire-nvr/db)`
```

**Comment by scottlamb** [comment]
Slight correction: 0.13.5 wasn't yanked either.

(I just want to add a dep to my software, but I can't seem to get it to add the new thing to `Cargo.lock` without seeing the ring yankedness and bailing. argh.)

**Comment by samscott89** [comment]
Should be fixed in latest release (finally decided to go ahead an push it as 0.1). Also removed the dependency on ring-pwhash in favour of the scrypt crate, which should hopefully help with future ring dependency issues...
