### ISSUE TITLE
Should migrate_hash return bool?

### ISSUE THREAD

**Issue by lnicola** [libpasta/libpasta#4]
I haven't used `libpasta`, but it seems nifty. I have a question about the API, though. Is `migrate_hash` a no-op when no migration was needed? In that case it might be better to tell the caller whether anything was done.

Of course, the caller can save the old one and compare them to know if it needs to be updated, but it's still an inconvenience.

**Comment by samscott89** [comment]
Hey, thanks for thi wile interest!

The mechanism to determine if an update is needed is still in process (need to define a partial order on Algorithm, or at least implement `PartialOrd`). But yes, that is the idea.

I like the idea of returning a `bool`, but I'm still debating whether acting on mutable `String`s is the best way forwards? I had envisioned it being used like [this](https://github.com/libpasta/libpasta/blob/132aa0db633c711bd027565931fe6995d19b55e5/examples/migrate_password.rs#L13). But seeing some real-world usage might suggest an alternate approach (taking in `&str`, returning `String`).

In the meantime, however, adding the `bool` return seems like a good idea.

**Comment by lnicola** [comment]
Then maybe returning `Option<String>` would be an option (no pun intended). I think that would work best, as migrations are pretty rare and the hash might be borrowed.

I've seen the example on the website, but it seems to assume some sort of magical ORM or at least change tracking.

**Comment by samscott89** [comment]
Yeah, I think that might be the best way forwards. In place string mutation just seems like an anti pattern in almost any language.

**Comment by samscott89** [comment]
I couldn't see any obvious way to return the three options in a foolproof way without creating a new enum.
Three options being: validated/hash migrated; validated/no migration needed; password incorrect. Technically it could be done as a `Result<Option<String>>`, but I don't consider `Failed` as an error state.
I like the explicitness needed to handle the three cases as can be seen [here](https://github.com/libpasta/libpasta/pull/5/files#diff-f320a5a65674d79417c608f7648f7cdfR24).

**Comment by lnicola** [comment]
That actually looks rather reasonable 😄 .
